DROP TABLE IF EXISTS STOCK;
CREATE  TABLE "STOCK"(
    "ID" BIGINT auto_increment primary key,
    "CLOSE" DOUBLE ,
    "DATE" DATE,
    "DAYS_TO_NEXT_DIVIDEND" INTEGER ,
    "HIGH" DOUBLE ,
    "LOW" DOUBLE ,
    "NEXT_WEEKS_CLOSE" DOUBLE ,
    "NEXT_WEEKS_OPEN" DOUBLE ,
    "OPEN" DOUBLE ,
    "PERCENT_CHANGE_VOLUME_OVER_LAST_WK" DOUBLE ,
    "PERCENT_CHANGE_NEXT_WEEKS_PRICE" DOUBLE ,
    "PERCENT_CHANGE_PRICE" DOUBLE ,
    "PERCENT_RETURN_NEXT_DIVIDEND" DOUBLE ,
    "PREVIOUS_WEEKS_VOLUME" BIGINT ,
    "QUARTER" INTEGER ,
    "STOCK" VARCHAR(255),
    "VOLUME" BIGINT 
);